name: matrimony
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.12
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  animated_text_kit: ^4.3.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.3
  lottie: any
  image_picker: ^1.2.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  change_app_package_name: ^1.5.0
  photo_view: ^0.15.0
  in_app_update: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/